import = [
  "~/.config/alacritty/themes/everforest_dark_medium.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = true

[window.dimensions]
columns = 130
lines = 40 

[window.padding]
x = 2
y = 2 

[font]
size = 18 
offset = { x=0, y=0 }

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Medium"
