#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    current_user=$(whoami)
    directories=(~/dev)

    if [[ "$current_user" == "jacob.matthews" ]]; then
        directories+=(~/euc)
    else
        directories+=(~/net)
    fi

    find_results=$(find ${directories[@]} -mindepth 1 -maxdepth 1 -type d)
    find_results+=$'\n'"$HOME/.config"

    if [[ "$current_user" == "jacob.matthews" ]]; then
      find_results+=$'\n'"$HOME/euc"
    else
      find_results+=$'\n'"$HOME/net"
    fi

    selected=$(echo "$find_results" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

parent_dir=$(basename "$(dirname "$selected")")
selected_dir=$(basename "$selected")

selected_name=$(echo "${parent_dir}_${selected_dir}" | tr . _)

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected 'nvim'
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected 'nvim'
fi

if [[ -z $TMUX ]]; then
    tmux attach -t $selected_name
else
    tmux switch-client -t $selected_name
fi
